server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlserver://SERVIDOR_REAL:1433;databaseName=academia;encrypt=true;trustServerCertificate=false
    username: usuario_prod
    password: ${DB_PASSWORD}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate